import type { Produto } from "@/lib/catalog/types";

/* Example frames — TRI-MOD-A/B/C keep parity with `/apresentacao` slide 06 and
   `scripts/verificar-fase-0.mts`. Every entry is `exemplo: true`; measurements are
   plausible mm values for `Numeracao`, not verified Trísion product data. */
export const produtos = [
  {
    nome: "Modelo A",
    sku: "TRI-MOD-A",
    marca: "Trísion",
    colecaoSlug: "exemplo",
    categoria: "grau",
    formato: "quadrado",
    material: "acetato",
    cor: "preto",
    corHex: "#1A1A1A",
    genero: "unissex",
    medidas: { aro: 52, ponte: 18, haste: 145 },
    fotos: [],
    descricao:
      "Armação de acetato, formato quadrado. Produto de demonstração — não faz parte do catálogo real da Trísion.",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Modelo B",
    sku: "TRI-MOD-B",
    marca: "Trísion",
    colecaoSlug: "exemplo",
    categoria: "grau",
    formato: "redondo",
    material: "metal",
    cor: "dourado",
    corHex: "#CCA866",
    genero: "unissex",
    medidas: { aro: 49, ponte: 21, haste: 140 },
    fotos: [],
    descricao:
      "Armação de metal, formato redondo. Produto de demonstração — não faz parte do catálogo real da Trísion.",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Modelo C",
    sku: "TRI-MOD-C",
    marca: "Trísion",
    colecaoSlug: "exemplo",
    categoria: "grau",
    formato: "gatinho",
    material: "acetato",
    cor: "tartaruga",
    corHex: "#6B4423",
    genero: "feminino",
    medidas: { aro: 54, ponte: 17, haste: 145 },
    fotos: [],
    descricao:
      "Armação de acetato, formato gatinho. Produto de demonstração — não faz parte do catálogo real da Trísion.",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Noturno I",
    sku: "TRI-EX-04",
    marca: "Trísion",
    colecaoSlug: "noturna-exemplo",
    categoria: "grau",
    formato: "retangular",
    material: "acetato",
    cor: "grafite",
    corHex: "#3D3D3D",
    genero: "masculino",
    medidas: { aro: 55, ponte: 18, haste: 145 },
    fotos: [],
    descricao:
      "Retangular em acetato escuro — fictício, para testar filtro de material e coleção noturna.",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Noturno II",
    sku: "TRI-EX-05",
    marca: "Trísion",
    colecaoSlug: "noturna-exemplo",
    categoria: "grau",
    formato: "aviador",
    material: "metal",
    cor: "gunmetal",
    corHex: "#5C5C5C",
    genero: "unissex",
    medidas: { aro: 58, ponte: 14, haste: 140 },
    fotos: [],
    descricao:
      "Aviador em metal — produto de demonstração, numeração plausível, não especificação de fábrica.",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Noturno III",
    sku: "TRI-EX-06",
    marca: "Trísion",
    colecaoSlug: "noturna-exemplo",
    categoria: "grau",
    formato: "hexagonal",
    material: "titânio",
    cor: "prata",
    corHex: "#C0C0C0",
    genero: "feminino",
    medidas: { aro: 51, ponte: 19, haste: 135 },
    fotos: [],
    descricao:
      "Hexagonal em titânio — exemplo para cobrir material titânio e formato hexagonal no catálogo.",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Solar I",
    sku: "TRI-EX-07",
    marca: "Trísion",
    colecaoSlug: "solar-exemplo",
    categoria: "solar",
    formato: "aviador",
    material: "metal",
    cor: "dourado",
    corHex: "#CCA866",
    genero: "masculino",
    medidas: { aro: 57, ponte: 15, haste: 140 },
    fotos: [],
    descricao:
      "Solar aviador — demonstração. Sem preço; Consulte o valor no mostruário da revenda.",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Solar II",
    sku: "TRI-EX-08",
    marca: "Trísion",
    colecaoSlug: "solar-exemplo",
    categoria: "solar",
    formato: "gatinho",
    material: "acetato",
    cor: "âmbar",
    corHex: "#B8860B",
    genero: "feminino",
    medidas: { aro: 53, ponte: 20, haste: 145 },
    fotos: [],
    descricao:
      "Solar gatinho em acetato — fictício, exercita categoria solar e filtro de gênero feminino.",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Solar III",
    sku: "TRI-EX-09",
    marca: "Trísion",
    colecaoSlug: "solar-exemplo",
    categoria: "solar",
    formato: "quadrado",
    material: "TR90",
    cor: "verde oliva",
    corHex: "#556B2F",
    genero: "unissex",
    medidas: { aro: 50, ponte: 22, haste: 145 },
    fotos: [],
    descricao:
      "Quadrado em TR90 — produto de teste para material TR90 e categoria solar.",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Essencial I",
    sku: "TRI-EX-10",
    marca: "Trísion",
    colecaoSlug: "essenciais-exemplo",
    categoria: "grau",
    formato: "retangular",
    material: "acetato",
    cor: "havana",
    corHex: "#8B4513",
    genero: "unissex",
    medidas: { aro: 54, ponte: 17, haste: 140 },
    fotos: [],
    descricao:
      "Retangular clássico — demonstração na coleção essenciais, sem ligação a modelo comercial real.",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Essencial II",
    sku: "TRI-EX-11",
    marca: "Trísion",
    colecaoSlug: "essenciais-exemplo",
    categoria: "grau",
    formato: "redondo",
    material: "metal",
    cor: "preto fosco",
    corHex: "#2B2B2B",
    genero: "feminino",
    medidas: { aro: 48, ponte: 20, haste: 140 },
    fotos: [],
    descricao:
      "Redondo fino em metal — exemplo para mostruários com perfil mais discreto.",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Essencial III",
    sku: "TRI-EX-12",
    marca: "Trísion",
    colecaoSlug: "essenciais-exemplo",
    categoria: "clip-on",
    formato: "quadrado",
    material: "metal",
    cor: "preto",
    corHex: "#1A1A1A",
    genero: "masculino",
    medidas: { aro: 52, ponte: 18, haste: 145 },
    fotos: [],
    descricao:
      "Clip-on quadrado — único exemplo de categoria clip-on no catálogo fictício.",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Essencial IV",
    sku: "TRI-EX-13",
    marca: "Trísion",
    colecaoSlug: "essenciais-exemplo",
    categoria: "grau",
    formato: "hexagonal",
    material: "acetato",
    cor: "vinho",
    corHex: "#722F37",
    genero: "feminino",
    medidas: { aro: 52, ponte: 18, haste: 145 },
    fotos: [],
    descricao:
      "Hexagonal em acetato colorido — demonstração para swatch de cor e formato.",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Essencial V",
    sku: "TRI-EX-14",
    marca: "Trísion",
    colecaoSlug: "essenciais-exemplo",
    categoria: "grau",
    formato: "aviador",
    material: "titânio",
    cor: "bronze",
    corHex: "#8C6B4A",
    genero: "masculino",
    medidas: { aro: 56, ponte: 16, haste: 145 },
    fotos: [],
    descricao:
      "Aviador leve em titânio — fictício, combina material premium com formato clássico.",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Essencial VI (descontinuado)",
    sku: "TRI-EX-15",
    marca: "Trísion",
    colecaoSlug: "essenciais-exemplo",
    categoria: "grau",
    formato: "gatinho",
    material: "TR90",
    cor: "rosa antigo",
    corHex: "#BC8F8F",
    genero: "feminino",
    medidas: { aro: 53, ponte: 17, haste: 140 },
    fotos: [],
    descricao:
      "Modelo descontinuado de demonstração — não aparece no catálogo ativo, só para testar status no admin.",
    status: "descontinuado",
    exemplo: true,
  },
] as const satisfies readonly Produto[];
