import type { Revendedor } from "@/lib/catalog/types";

/** Mock resellers for Fase 0 — exercises the storefront, directory filter, and tenancy
 * seam ahead of Fase 1's Payload-backed `revendedores`. Fictional shops, obviously so
 * (`exemplo: true`), same license as `content/produtos.ts`. */
export const revendedores = [
  {
    nome: "Ótica Exemplo",
    slug: "otica-exemplo",
    cidade: "Volta Redonda",
    uf: "RJ",
    whatsapp: "",
    instagram: "",
    sobre:
      "Loja de demonstração para o scaffold do storefront. Não é uma revenda real da Trísion.",
    endereco: "Rua Exemplo, 100 — Centro, Volta Redonda — RJ",
    horarios: "Seg–Sex 9h–18h · Sáb 9h–13h",
    retrato: "",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Ótica Demonstração",
    slug: "otica-demonstracao",
    cidade: "São Paulo",
    uf: "SP",
    whatsapp: "",
    instagram: "",
    sobre:
      "Segunda loja de demonstração — só para exercitar o filtro por cidade e UF no diretório.",
    endereco: "Av. Exemplo, 500 — Bela Vista, São Paulo — SP",
    horarios: "Seg–Sex 10h–19h",
    retrato: "",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Loja Exemplo",
    slug: "loja-exemplo",
    cidade: "Curitiba",
    uf: "PR",
    whatsapp: "",
    instagram: "",
    sobre: "Terceira loja fictícia — outra UF no filtro, outro slug no storefront.",
    endereco: "Rua Demonstração, 42 — Batel, Curitiba — PR",
    horarios: "Seg–Sex 9h–18h · Sáb 9h–12h",
    retrato: "",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Ótica Vidro (exemplo)",
    slug: "otica-vidro-exemplo",
    cidade: "Niterói",
    uf: "RJ",
    whatsapp: "",
    instagram: "",
    sobre:
      "Quarta revenda fictícia — mesma UF que Volta Redonda, cidade diferente, para o filtro por município.",
    endereco: "Rua da Praia, 220 — Icaraí, Niterói — RJ",
    horarios: "Seg–Sex 9h–19h · Sáb 9h–14h",
    retrato: "",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Visão Centro (exemplo)",
    slug: "visao-centro-exemplo",
    cidade: "Belo Horizonte",
    uf: "MG",
    whatsapp: "",
    instagram: "",
    sobre:
      "Loja de demonstração em Minas — mostruário focado em formatos clássicos e linha noturna.",
    endereco: "Av. Afonso Pena, 1200 — Centro, Belo Horizonte — MG",
    horarios: "Seg–Sex 8h30–18h",
    retrato: "",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Olhar Sul (exemplo)",
    slug: "olhar-sul-exemplo",
    cidade: "Porto Alegre",
    uf: "RS",
    whatsapp: "",
    instagram: "",
    sobre:
      "Revenda fictícia no Rio Grande do Sul — exercita UF RS no diretório de revendedores.",
    endereco: "Rua dos Andradas, 800 — Centro Histórico, Porto Alegre — RS",
    horarios: "Seg–Sex 9h–18h · Sáb 9h–13h",
    retrato: "",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Óptica Baiana (exemplo)",
    slug: "optica-baiana-exemplo",
    cidade: "Salvador",
    uf: "BA",
    whatsapp: "",
    instagram: "",
    sobre:
      "Loja fictícia na Bahia — catálogo solar mais presente no mostruário de teste.",
    endereco: "Rua Chile, 15 — Pelourinho, Salvador — BA",
    horarios: "Seg–Sex 9h–17h",
    retrato: "",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Visão Recife (exemplo)",
    slug: "visao-recife-exemplo",
    cidade: "Recife",
    uf: "PE",
    whatsapp: "",
    instagram: "",
    sobre:
      "Oitava revenda de demonstração — nordeste no mapa de filtros, mostruário compacto.",
    endereco: "Rua do Bom Jesus, 200 — Recife Antigo, Recife — PE",
    horarios: "Seg–Sex 9h–18h",
    retrato: "",
    status: "ativo",
    exemplo: true,
  },
  {
    nome: "Ótica Pausada (exemplo)",
    slug: "otica-pausada-exemplo",
    cidade: "Campinas",
    uf: "SP",
    whatsapp: "",
    instagram: "",
    sobre:
      "Revenda fictícia com status pausado — não deve aparecer no diretório de revendedores ativos.",
    endereco: "Rua Barão de Jaguara, 300 — Centro, Campinas — SP",
    horarios: "Temporariamente fechada",
    retrato: "",
    status: "pausado",
    exemplo: true,
  },
] as const satisfies readonly Revendedor[];
